local dap = require 'dap'
local dapui = require 'dapui'
local dwidgts = require 'dap.ui.widgets'
local keymap = vim.keymap

-- dap keymaps
keymap.set('n', '<leader>do', function()
  dapui.open()
end, { desc = 'Open debugging UI' })

keymap.set('n', '<leader>dc', function()
  dapui.close()
end, { desc = 'Close debugging UI' })

keymap.set('n', '<f6>', function()
  dap.step_over()
end, { desc = 'Step Over function' })
keymap.set('n', '<f7>', function()
  dap.step_into()
end, { desc = 'Step Into function' })
keymap.set('n', '<f8>', function()
  dap.step_out()
end, { desc = 'Step Out of function' })

keymap.set('n', '<leader>db', function()
  dap.toggle_breakpoint()
end, { desc = 'toggle breakpoint' })

keymap.set('n', '<leader>df', function()
  dwidgts.centered_float(dwidgts.frames)
end, { desc = 'display frames' })
keymap.set('n', '<leader>dS', function()
  dwidgts.centered_float(dwidgts.scopes)
end, { desc = 'display Scopes' })

-- rustaceanvim keymaps
keymap.set('n', '<leader>rrun', function()
  vim.cmd.RustLsp 'runnables'
end, { desc = 'Runnables' })
keymap.set('n', '<leader>ru', function()
  vim.cmd.RustLsp('moveItem', 'up')
end, { desc = 'move item up' })
keymap.set('n', '<leader>rd', function()
  vim.cmd.RustLsp('moveItem', 'down')
end, { desc = 'move item down' })
keymap.set('n', '<leader>rha', function()
  vim.cmd.RustLsp('hover', 'actions')
end, { desc = 'Hover Actions' })
keymap.set('n', '<leader>rhr', function()
  vim.cmd.RustLsp('hover', 'range')
end, { desc = 'Hover Range' })
keymap.set('n', '<leader>re', function()
  vim.cmd.RustLsp 'explainError'
end, { desc = 'Explain Error' })
keymap.set('n', '<leader>rrD', function()
  vim.cmd.RustLsp 'renderDiagnostic'
end, { desc = 'Toggle Inlay Hints' })
keymap.set('n', '<leader>rc', function()
  vim.cmd.RustLsp 'openCargo'
end, { desc = 'Open Cargo' })
keymap.set('n', '<leader>rj', function()
  vim.cmd.RustLsp 'joinLines'
end, { desc = 'Join Lines' })
keymap.set('n', '<leader>rs', function()
  vim.cmd.RustLsp('ssr', '<query>')
end, { desc = 'Search and replace' })
keymap.set('n', '<leader>rS', function()
  vim.cmd.RustLsp 'syntaxTree'
end, { desc = 'syntax Tree' })

-- which-key keymaps
keymap.set('n', '<leader>?', function()
  require('which-key').show { global = false }
end, { desc = 'Buffer Local Keymaps (which-key)' })

-- neotest keymaps
keymap.set('n', '<leader>tt', function()
  require('neotest').run.run(vim.fn.expand '%')
end, { desc = 'Run File' })
keymap.set('n', '<leader>tT', function()
  require('neotest').run.run(vim.uv.cwd())
end, { desc = 'Run All Test Files' })
keymap.set('n', '<leader>tr', function()
  require('neotest').run.run()
end, { desc = 'Run Nearest' })
keymap.set('n', '<leader>tl', function()
  require('neotest').run.run_last()
end, { desc = 'Run Last' })
keymap.set('n', '<leader>ts', function()
  require('neotest').summary.toggle()
end, { desc = 'Toggle Summary' })
keymap.set('n', '<leader>to', function()
  require('neotest').output.open { enter = true, auto_close = true }
end, { desc = 'Show Output' })
keymap.set('n', '<leader>tO', function()
  require('neotest').output_panel.toggle()
end, { desc = 'Toggle Output Panel' })
keymap.set('n', '<leader>tS', function()
  require('neotest').run.stop()
end, { desc = 'Stop' })
keymap.set('n', '<leader>tw', function()
  require('neotest').watch.toggle(vim.fn.expand '%')
end, { desc = 'Toggle Watch' })

keymap.set('n', '<leader><space>', function()
  Snacks.picker.smart()
end, { desc = 'Smart Find Files' })
keymap.set('n', '<leader>,', function()
  Snacks.picker.buffers()
end, { desc = 'Buffers' })
keymap.set('n', '<leader>/', function()
  Snacks.picker.grep()
end, { desc = 'Grep' })
keymap.set('n', '<leader>:', function()
  Snacks.picker.command_history()
end, { desc = 'Command History' })
keymap.set('n', '<leader>n', function()
  Snacks.picker.notifications()
end, { desc = 'Notification History' })
keymap.set('n', '<leader>e', function()
  Snacks.explorer()
end, { desc = 'File Explorer' })
-- find
keymap.set('n', '<leader>fb', function()
  Snacks.picker.buffers()
end, { desc = 'Buffers' })
keymap.set('n', '<leader>fc', function()
  Snacks.picker.files { cwd = vim.fn.stdpath 'config' }
end, { desc = 'Find Config File' })
keymap.set('n', '<leader>ff', function()
  Snacks.picker.files()
end, { desc = 'Find Files' })
keymap.set('n', '<leader>fg', function()
  Snacks.picker.git_files()
end, { desc = 'Find Git Files' })
keymap.set('n', '<leader>fp', function()
  Snacks.picker.projects()
end, { desc = 'Projects' })
keymap.set('n', '<leader>fr', function()
  Snacks.picker.recent()
end, { desc = 'Recent' })
keymap.set('n', '<leader>gb', function()
  Snacks.picker.git_branches()
end, { desc = 'Git Branches' })
keymap.set('n', '<leader>gl', function()
  Snacks.picker.git_log()
end, { desc = 'Git Log' })
keymap.set('n', '<leader>gL', function()
  Snacks.picker.git_log_line()
end, { desc = 'Git Log Line' })
keymap.set('n', '<leader>gs', function()
  Snacks.picker.git_status()
end, { desc = 'Git Status' })
keymap.set('n', '<leader>gS', function()
  Snacks.picker.git_stash()
end, { desc = 'Git Stash' })
keymap.set('n', '<leader>gd', function()
  Snacks.picker.git_diff()
end, { desc = 'Git Diff (Hunks)' })
keymap.set('n', '<leader>gf', function()
  Snacks.picker.git_log_file()
end, { desc = 'Git Log File' })
keymap.set('n', '<leader>sB', function()
  Snacks.picker.grep_buffers()
end, { desc = 'Grep Open Buffers' })
keymap.set('n', '<leader>sg', function()
  Snacks.picker.grep()
end, { desc = 'Grep' })
keymap.set({ 'n', 'x' }, '<leader>sw', function()
  Snacks.picker.grep_word()
end, { desc = 'Visual selection or word' })
keymap.set('n', '<leader>s"', function()
  Snacks.picker.registers()
end, { desc = 'Registers' })
keymap.set('n', '<leader>s/', function()
  Snacks.picker.search_history()
end, { desc = 'Search History' })
keymap.set('n', '<leader>sa', function()
  Snacks.picker.autocmds()
end, { desc = 'Autocmds' })
keymap.set('n', '<leader>sb', function()
  Snacks.picker.lines()
end, { desc = 'Buffer Lines' })
keymap.set('n', '<leader>sc', function()
  Snacks.picker.command_history()
end, { desc = 'Command History' })
keymap.set('n', '<leader>sC', function()
  Snacks.picker.commands()
end, { desc = 'Commands' })
keymap.set('n', '<leader>sd', function()
  Snacks.picker.diagnostics()
end, { desc = 'Diagnostics' })
keymap.set('n', '<leader>sD', function()
  Snacks.picker.diagnostics_buffer()
end, { desc = 'Buffer Diagnostics' })
keymap.set('n', '<leader>sh', function()
  Snacks.picker.help()
end, { desc = 'Help Pages' })
keymap.set('n', '<leader>sH', function()
  Snacks.picker.highlights()
end, { desc = 'Highlights' })
keymap.set('n', '<leader>si', function()
  Snacks.picker.icons()
end, { desc = 'Icons' })
keymap.set('n', '<leader>sj', function()
  Snacks.picker.jumps()
end, { desc = 'Jumps' })
keymap.set('n', '<leader>sk', function()
  Snacks.picker.keymaps()
end, { desc = 'Keymaps' })
keymap.set('n', '<leader>sl', function()
  Snacks.picker.loclist()
end, { desc = 'Location List' })
keymap.set('n', '<leader>sm', function()
  Snacks.picker.marks()
end, { desc = 'Marks' })
keymap.set('n', '<leader>sM', function()
  Snacks.picker.man()
end, { desc = 'Man Pages' })
keymap.set('n', '<leader>sp', function()
  Snacks.picker.lazy()
end, { desc = 'Search for Plugin Spec' })
keymap.set('n', '<leader>sq', function()
  Snacks.picker.qflist()
end, { desc = 'Quickfix List' })
keymap.set('n', '<leader>sR', function()
  Snacks.picker.resume()
end, { desc = 'Resume' })
keymap.set('n', '<leader>su', function()
  Snacks.picker.undo()
end, { desc = 'Undo History' })
keymap.set('n', '<leader>uC', function()
  Snacks.picker.colorschemes()
end, { desc = 'Colorschemes' })
keymap.set('n', 'gd', function()
  Snacks.picker.lsp_definitions()
end, { desc = 'Goto Definition' })
keymap.set('n', 'gD', function()
  Snacks.picker.lsp_declarations()
end, { desc = 'Goto Declaration' })
keymap.set('n', 'gr', function()
  Snacks.picker.lsp_references()
end, { nowait = true, desc = 'References' })
keymap.set('n', 'gI', function()
  Snacks.picker.lsp_implementations()
end, { desc = 'Goto Implementation' })
keymap.set('n', 'gy', function()
  Snacks.picker.lsp_type_definitions()
end, { desc = 'Goto T[y]pe Definition' })
keymap.set('n', '<leader>ss', function()
  Snacks.picker.lsp_symbols()
end, { desc = 'LSP Symbols' })
keymap.set('n', '<leader>sS', function()
  Snacks.picker.lsp_workspace_symbols()
end, { desc = 'LSP Workspace Symbols' })
keymap.set('n', '<leader>z', function()
  Snacks.zen()
end, { desc = 'Toggle Zen Mode' })
keymap.set('n', '<leader>Z', function()
  Snacks.zen.zoom()
end, { desc = 'Toggle Zoom' })
keymap.set('n', '<leader>.', function()
  Snacks.scratch()
end, { desc = 'Toggle Scratch Buffer' })
keymap.set('n', '<leader>S', function()
  Snacks.scratch.select()
end, { desc = 'Select Scratch Buffer' })
keymap.set('n', '<leader>n', function()
  Snacks.notifier.show_history()
end, { desc = 'Notification History' })
keymap.set('n', '<leader>bd', function()
  Snacks.bufdelete()
end, { desc = 'Delete Buffer' })
keymap.set('n', '<leader>cR', function()
  Snacks.rename.rename_file()
end, { desc = 'Rename File' })
keymap.set({ 'n', 'v' }, '<leader>gB', function()
  Snacks.gitbrowse()
end, { desc = 'Git Browse' })
keymap.set('n', '<leader>gg', function()
  Snacks.lazygit()
end, { desc = 'Lazygit' })
keymap.set('n', '<leader>un', function()
  Snacks.notifier.hide()
end, { desc = 'Dismiss All Notifications' })
keymap.set('n', '<c-/>', function()
  Snacks.terminal()
end, { desc = 'Toggle Terminal' })
keymap.set('n', '<c-_>', function()
  Snacks.terminal()
end, { desc = 'which_key_ignore' })
keymap.set({ 'n', 't' }, ']]', function()
  Snacks.words.jump(vim.v.count1)
end, { desc = 'Next Reference' })
keymap.set({ 'n', 't' }, '[[', function()
  Snacks.words.jump(-vim.v.count1)
end, { desc = 'Prev Reference' })
keymap.set('n', '<leader>N', function()
  Snacks.win {
    file = vim.api.nvim_get_runtime_file('doc/news.txt', false)[1],
    width = 0.6,
    height = 0.6,
    wo = {
      spell = false,
      wrap = false,
      signcolumn = 'yes',
      statuscolumn = ' ',
      conceallevel = 3,
    },
  }
end, { desc = 'Neovim News' })

-- telescope github keymaps
keymap.set('n', '<leader>tgi', '<cmd>Telescope gh issues<cr>', { desc = 'Github issues' })
keymap.set('n', '<leader>tgp', '<cmd>Telescope gh pull_request<cr>', { desc = 'Github PR View' })
keymap.set('n', '<leader>tgg', '<cmd>Telescope gh gist<cr>', { desc = 'Github gists' })
keymap.set('n', '<leader>tgw', '<cmd>Telescope gh run<cr>', { desc = 'Github workflow runs' })
keymap.set('n', '<leader>tgs', '<cmd>Telescope gh secret<cr>', { desc = 'Github repo Secrets' })

-- trouble keymaps
keymap.set('n', '<leader>xx', '<cmd>Trouble diagnostics toggle<cr>', { desc = 'Diagnostics (Trouble)' })
keymap.set('n', '<leader>xX', '<cmd>Trouble diagnostics toggle filter.buf=0<cr>', { desc = 'Buffer Diagnostics (Trouble)' })
keymap.set('n', '<leader>cs', '<cmd>Trouble symbols toggle focus=false<cr>', { desc = 'Symbols (Trouble)' })
keymap.set('n', '<leader>cl', '<cmd>Trouble lsp toggle focus=false win.position=right<cr>', { desc = 'LSP Definitions / references / ... (Trouble)' })
keymap.set('n', '<leader>xL', '<cmd>Trouble loclist toggle<cr>', { desc = 'Location List (Trouble)' })
keymap.set('n', '<leader>xQ', '<cmd>Trouble qflist toggle<cr>', { desc = 'Quickfix List (Trouble)' })
